Treat invokeinterface bridges similarly to invokespecial
In both cases we need to avoid using invokesuper. For interface bridges,
using invokesuper will fail since the method being bridged to is in a
superinterface, not a superclass.

Starting in Java 8, javac emits default bridge methods in interfaces,
which use invokeinterface to bridge to the target method.

Without this fix, the included test case fails with:

```
Caused by: java.lang.NoSuchMethodError: java.lang.Object.f(Ljava/lang/Object;)V
    at B$$EnhancerByCGLIB$$7aa3e8e0.f(<generated>)
    ... 28 more
```